function GapFillAGORADraftModels(percent,probType,solveTime)
% This code gapfills the draft models generated by randomly removing the
% reactions in the AGORA models
    changeCobraSolverParams('LP', 'feasTol', 1e-9);
    changeCobraSolverParams('LP', 'optTol', 1e-9);
    IncompAGORA = ['./IncompModels_',num2str(percent)];
    p = dir(IncompAGORA);
    p = {p(3:end).name}';
    tol = 1e-5;
    load('./AGORAmodel.mat') % consistent universal model of AGORA db
    mkdir(['./GapfilledModels_',probType,'_',num2str(percent)])
    for i=1:numel(p)
        load([IncompAGORA,'/',p{i}])
        if ~any(model.c)
            error('No biomass reaction in the draft model')
        end
        % adding the biomass reaction to the universal model
        bioR = printRxnFormula(model,'rxnAbbrList',model.rxns(find(model.c)),...
            'printFlag',false);
        Utemp = ConsUmodel;
        Utemp = addReaction(Utemp,model.rxns{find(model.c)},'reactionFormula',bioR{1},...
                'lowerBound',0,'upperBound',1000);
        % getting the core reactions
        core = find(ismember(Utemp.rxns,model.rxns));
        if numel(core)~=numel(model.rxns)
            error('Missing consistent reactions in the universal model')
        end
        model = sprintcore(Utemp,core,tol,'consistency',[],1,[],probType,solveTime);
        save(['./GapfilledModels_',probType,'_',num2str(percent),'/',p{i}],'model')
        clear model
    end

end
